name: Setup
permissions:
  contents: read
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
      with:
        run_install: false

    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: '.nvmrc'
        registry-url: https://registry.npmjs.org
        cache: pnpm

    # For provenance https://docs.npmjs.com/generating-provenance-statements#prerequisites
    - name: Install npm 9.9.4
      run: npm install -g npm@9.9.4
      shell: bash

    - name: Install node modules
      run: pnpm install --frozen-lockfile
      shell: bash
