const GENERIC_ERROR_MESSAGE = 'Something went wrong. Please try again.';
// Most likely EOAexport const genericErrorMessage = 'Something went wrong. Please try again.';
const METHOD_NOT_SUPPORTED_ERROR_SUBSTRING = 'this request method is not supported';
const SEND_CALLS_NOT_SUPPORTED_ERROR = 'SEND_CALLS_NOT_SUPPORTED_ERROR';
const TRANSACTION_TYPE_CALLS = 'TRANSACTION_TYPE_CALLS';
const TRANSACTION_TYPE_CONTRACTS = 'TRANSACTION_TYPE_CONTRACTS';
export { GENERIC_ERROR_MESSAGE, METHOD_NOT_SUPPORTED_ERROR_SUBSTRING, SEND_CALLS_NOT_SUPPORTED_ERROR, TRANSACTION_TYPE_CALLS, TRANSACTION_TYPE_CONTRACTS };
//# sourceMappingURL=constants.js.map
