import './theme.css';
import '@coinbase/onchainkit/styles.css';
import type { Metadata, Viewport } from 'next';
import './globals.css';
import { Providers } from './providers';

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: 'MiniKit',
    description:
      'Generated by `create-onchain --mini`, a Next.js template for MiniKit',
    other: {
      'fc:frame': JSON.stringify({
        version: 'next',
        imageUrl: 'https://onchainkit.xyz/playground/snake.png',
        button: {
          title: 'Launch MiniKit',
          action: {
            type: 'launch_frame',
            name: 'MiniKit',
            url: 'https://onchainkit.xyz/playground/minikit',
            splashImageUrl: 'https://onchainkit.xyz/playground/snake.png',
            splashBackgroundColor: '#FFFFFF',
          },
        },
      }),
    },
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <Providers>{children}</Providers>;
}
