export const GENERAL_PAY_ERROR_CODE = 'PAY_ERROR';
export const PAY_TOO_MANY_REQUESTS_ERROR_CODE = 'PAY_TOO_MANY_REQUESTS_ERROR';
export const PAY_INVALID_CHARGE_ERROR_CODE = 'PAY_INVALID_CHARGE_ERROR';
export const PAY_INVALID_PARAMETER_ERROR_CODE = 'PAY_INVALID_PARAMETER_ERROR';
export const UNCAUGHT_HYDRATE_CHARGE_ERROR_CODE =
  'UNCAUGHT_HYDRATE_CHARGE_ERROR';
