const FALLBACK_DEFAULT_MAX_SLIPPAGE = 3;
const GENERAL_SWAP_ERROR_CODE = 'SWAP_ERROR';
const GENERAL_SWAP_QUOTE_ERROR_CODE = 'SWAP_QUOTE_ERROR';
const GENERAL_SWAP_BALANCE_ERROR_CODE = 'SWAP_BALANCE_ERROR';
const LOW_LIQUIDITY_ERROR_CODE = 'SWAP_QUOTE_LOW_LIQUIDITY_ERROR';
const PERMIT2_CONTRACT_ADDRESS = '0x000000000022D473030F116dDEE9F6B43aC78BA3';
const TOO_MANY_REQUESTS_ERROR_CODE = 'TOO_MANY_REQUESTS_ERROR';
const UNCAUGHT_SWAP_QUOTE_ERROR_CODE = 'UNCAUGHT_SWAP_QUOTE_ERROR';
const UNCAUGHT_SWAP_ERROR_CODE = 'UNCAUGHT_SWAP_ERROR';
const UNIVERSALROUTER_CONTRACT_ADDRESS = '0x3fC91A3afd70395Cd496C647d5a6CC9D4B2b7FAD';
const USER_REJECTED_ERROR_CODE = 'USER_REJECTED';
let SwapMessage = /*#__PURE__*/function (SwapMessage) {
  SwapMessage["BALANCE_ERROR"] = "Error fetching token balance";
  SwapMessage["CONFIRM_IN_WALLET"] = "Confirm in wallet";
  SwapMessage["FETCHING_QUOTE"] = "Fetching quote...";
  SwapMessage["FETCHING_BALANCE"] = "Fetching balance...";
  SwapMessage["INCOMPLETE_FIELD"] = "Complete the fields to continue";
  SwapMessage["INSUFFICIENT_BALANCE"] = "Insufficient balance";
  SwapMessage["LOW_LIQUIDITY"] = "Insufficient liquidity for this trade.";
  SwapMessage["SWAP_IN_PROGRESS"] = "Swap in progress...";
  SwapMessage["TOO_MANY_REQUESTS"] = "Too many requests. Please try again later.";
  SwapMessage["USER_REJECTED"] = "User rejected the transaction";
  return SwapMessage;
}({});
export { FALLBACK_DEFAULT_MAX_SLIPPAGE, GENERAL_SWAP_BALANCE_ERROR_CODE, GENERAL_SWAP_ERROR_CODE, GENERAL_SWAP_QUOTE_ERROR_CODE, LOW_LIQUIDITY_ERROR_CODE, PERMIT2_CONTRACT_ADDRESS, SwapMessage, TOO_MANY_REQUESTS_ERROR_CODE, UNCAUGHT_SWAP_ERROR_CODE, UNCAUGHT_SWAP_QUOTE_ERROR_CODE, UNIVERSALROUTER_CONTRACT_ADDRESS, USER_REJECTED_ERROR_CODE };
//# sourceMappingURL=constants.js.map
