name: Release (Canary)
on:
  workflow_dispatch:

jobs:
  canary:
    name: Release canary
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Setup'
        uses: ./.github/actions/setup

      - name: Set version
        run: |
          npm --no-git-tag-version version $(npm pkg get version | sed 's/"//g')-$(git branch --show-current | tr -cs '[:alnum:]-' '-' | tr '[:upper:]' '[:lower:]' | sed 's/-$//').$(date +'%Y%m%dT%H%M%S')

      - name: Build
        shell: bash
        run: pnpm --filter @coinbase/onchainkit build

      - name: Set deployment token
        run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"

      - name: Publish to npm
        run: |
          npm publish --tag $(git branch --show-current | tr -cs '[:alnum:]-' '-' | tr '[:upper:]' '[:lower:]' | sed 's/-$//')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
