name: CLI Test

on:
  push:
    branches:
      - main
    paths:
      - 'packages/create-onchain/**'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/create-onchain/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: 'Setup'
        uses: ./.github/actions/setup

      - name: Setup Bun
        uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1.2.2
        with:
          bun-version: latest

      - name: Install dependencies
        run: pnpm f:create install

      - name: Run CLI tests
        run: pnpm f:create test:coverage
