name: CLI Test

on:
  push:
    branches:
      - main
    paths:
      - 'packages/create-onchain/**'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/create-onchain/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Setup'
        uses: ./.github/actions/setup

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: pnpm f:create install

      - name: Run CLI tests
        run: pnpm f:create test:coverage
