name: "Pull Request Labeler"
on:
  pull_request:
    branches: ['main', 'develop']

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
