name: Version 🔖

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  version:
    name: Release
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Setup'
        uses: ./.github/actions/setup

      - name: Build
        shell: bash
        run: pnpm f:ock build

      - name: Get version
        shell: bash
        run: pnpm f:ock get-next-version

      - name: Set deployment token
        run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"

      - name: Set Version
        id: set_version
        run: |
          VERSION=$(cat packages/onchainkit/dist/version.txt)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # https://pnpm.io/using-changesets
      - name: Handle Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          title: 'chore: version packages v${{ steps.set_version.outputs.version }} 🌊'
          commit: 'chore: version packages v${{ steps.set_version.outputs.version }} 🌊'
          publish: pnpm release:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
