name: Release alpha version

on:
  push:
    branches:
      - main
      - '**--alpha'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-alpha:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Setup'
        uses: ./.github/actions/setup

      - name: Build
        shell: bash
        run: pnpm f:ock build

      - name: Set deployment token
        run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"

      - name: Publish alpha version
        shell: bash
        run: pnpm f:ock get-next-version
